language: ruby
rvm: 2.3
script:
  - bundle exec jekyll build
  - bundle exec pannier process
before_deploy:
  - tar -C _site -czvf site.tar.gz .
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: site.tar.gz
  skip_cleanup: true
  release_number: $TRAVIS_BUILD_NUMBER
  on:
    branch: master
