language: ruby
rvm: 2.3
branches:
  except:
    - /^[0-9]+$/

before_script:
  - export TRAVIS_TAG=${TRAVIS_BUILD_NUMBER}
  - echo "release_path: https://github.com/$TRAVIS_REPO_SLUG/releases/tag/$TRAVIS_TAG" >> _data/build.yml
  - echo "build_path: https://travis-ci.org/$TRAVIS_REPO_SLUG/builds/$TRAVIS_BUILD_ID" >> _data/build.yml
script:
  - bundle exec pannier process
  - bundle exec jekyll build

before_deploy:
  - tar -C _site -czvf site.tar.gz .
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: site.tar.gz
  skip_cleanup: true
  on:
    branch: master
