language: ruby
rvm: 2.3
script:
  - bundle exec jekyll build
  - bundle exec pannier process
before_deploy:
  - tar -czvf site.tar.gz _site
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: site.tar.gz
  skip_cleanup: true
  on:
    branch: master
