markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "strikethrough", "superscript", "smart", "footnotes"]
highlighter: pygments
permalink: /:year/:month/:day/:title
tag_layout: tag
tag_directory: tags
title: Joe Corcoran
description: Articles
url: https://corcoran.online
email: joe@corcoran.online
exclude: ["Gemfile", "Gemfile.lock", ".assets.rb", "assets", "bin", "vendor"]
