markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "strikethrough", "superscript", "smart"]
pygments: true
permalink: /:year/:month/:day/:title
tag_layout: tag
tag_directory: tags
title: "Joe Corcoran"
description: "Articles on programming"
url: "https://corcoran.io"
exclude: ["Capfile", "Gemfile", "Gemfile.lock", "Pannierfile", "assets", "bin"]
